### ISSUE TITLE
Compilation error on ruby 1.9.2

### ISSUE THREAD

**Issue by technoweenie** [miyucy/snappy#1]
I get this when trying to install with ruby 1.9.2 (installed via rvm).  Works fine on Ruby 1.8.7 and REE.

```
ruby-1.9.2-p136 $ gem install snappy
Building native extensions.  This could take a while...
ERROR:  Error installing snappy:
  ERROR: Failed to build gem native extension.

/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/bin/ruby extconf.rb
checking for main() in -lsnappy... no
checking for sys/mman.h... yes
checking for stdint.h... yes
checking for stddef.h... yes
checking for main() in -lstdc++... yes
creating Makefile

make
g++ -I. -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1/x86_64-darwin10.5.0 -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1/ruby/backward -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1 -I. -DHAVE_SYS_MMAN_H -DHAVE_STDINT_H -DHAVE_STDDEF_H -DHAVE_BUILTIN_EXPECT -DHAVE_BUILTIN_CTZ -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wshorten-64-to-32 -Wno-long-long  -fno-common -pipe   -o api.o -c api.cc
g++ -I. -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1/x86_64-darwin10.5.0 -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1/ruby/backward -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1 -I. -DHAVE_SYS_MMAN_H -DHAVE_STDINT_H -DHAVE_STDDEF_H -DHAVE_BUILTIN_EXPECT -DHAVE_BUILTIN_CTZ -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wshorten-64-to-32 -Wno-long-long  -fno-common -pipe   -o snappy-sinksource.o -c snappy-sinksource.cc
g++ -I. -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1/x86_64-darwin10.5.0 -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1/ruby/backward -I/Users/technoweenie/.rvm/rubies/ruby-1.9.2-p136/include/ruby-1.9.1 -I. -DHAVE_SYS_MMAN_H -DHAVE_STDINT_H -DHAVE_STDDEF_H -DHAVE_BUILTIN_EXPECT -DHAVE_BUILTIN_CTZ -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wshorten-64-to-32 -Wno-long-long  -fno-common -pipe   -o snappy-stubs-internal.o -c snappy-stubs-internal.cc
In file included from snappy-stubs-internal.cc:18:
snappy-stubs-internal.h:31:20: error: config.h: No such file or directory
make: *** [snappy-stubs-internal.o] Error 1


Gem files will remain installed in /Users/technoweenie/.rvm/gems/ruby-1.9.2-p136/gems/snappy-0.0.1 for inspection.
Results logged to /Users/technoweenie/.rvm/gems/ruby-1.9.2-p136/gems/snappy-0.0.1/ext/gem_make.out
```
